force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Projeto__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/DataInicio__c.field-meta.xml
<CustomField>
    <fullName>DataInicio__c</fullName>
    <label>Data de Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
                <default>true</default>
                <label>Novo</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projeto__c/fields/ValorProjeto__c.field-meta.xml
<CustomField>
    <fullName>ValorProjeto__c</fullName>
    <label>Valor do Projeto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountService.cls
public with sharing class AccountService {

    @AuraEnabled(cacheable=true)
    public static List<Projeto__c> obterProjetos(Id accountId){
        try {
            return [
                SELECT Id, Name, Conta__c, DataInicio__c, Status__c, ValorProjeto__c
                FROM Projeto__c
                WHERE Conta__c = :accountId
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Erro ao obter projetos: ' + e.getMessage());
        }
    }
}